### ISSUE TITLE
Windows - Uncaught Exception - A JavaScript error occurred in the main proccess

### ISSUE THREAD

**Issue by wallacecs007** [motdotla/oscnode#8]
OS: Windows
Version: 10.0.16299 Build 16299

Error Code:
![image](https://user-images.githubusercontent.com/26640765/36112605-79a5686a-0fe7-11e8-84ff-b8929876e244.png)

**Comment by motdotla** [comment]
Looks like the bug is here on Windows: https://github.com/motdotla/oscnode/blob/v0.3.2/src/index.js#L373

Windows must not have a concept of a dock. Probably just needs a conditional here when windows - to fix the problem.

**Comment by motdotla** [comment]
Fixed here https://github.com/motdotla/oscnode/pull/9

Fix will go out with next tagged release

**Comment by motdotla** [comment]
@wallacecs007 this should be fixed in `0.3.4`. Give it a try here https://github.com/motdotla/oscnode/releases/download/v0.3.4/oscnode-Setup-0.3.4.exe
